/* DtsxPackage → betl YAML. Holds the high-level walk; per-component
 * mappers live in Mappers/. */

using System;
using System.Collections.Generic;
using System.Linq;

namespace Betl.Dtsx2Yaml;

public static class Converter
{
    public static string PackageToYaml(DtsxPackage pkg, bool verbose = false)
    {
        var w = new YamlWriter();

        w.Line("# Generated by betl-dtsx2yaml from DTSX source.");
        w.Line("# Manual edits expected for: connection DSNs (provider-string");
        w.Line("# translation is approximate), upsert key columns (SSIS OLEDB");
        w.Line("# Destination has no key concept), and any TODO markers below.");
        w.Line();
        w.Line("betl: 1");
        w.Line("name: " + YamlWriter.Id(pkg.Name));

        EmitConnections(w, pkg);
        EmitParameters(w, pkg);
        EmitPipeline(w, pkg, verbose);

        return w.ToString();
    }

    static void EmitConnections(YamlWriter w, DtsxPackage pkg)
    {
        if (pkg.Connections.Count == 0) return;
        w.Line();
        w.Line("connections:");
        w.Indent(2);
        foreach (var c in pkg.Connections)
        {
            switch (c.CreationName)
            {
                case "OLEDB":
                case "ADO.NET":
                    Mappers.OledbConnection.Emit(w, c);
                    break;
                case "FLATFILE":
                    /* Flat file "connections" in SSIS hold the file path;
                     * we don't emit a betl connection for them — the path
                     * is inlined when the source/destination references it.
                     * Drop a comment so a verbose pass can see we noticed. */
                    w.Comment($"flat-file connection '{c.Name}' → inlined into csv.read / csv.write");
                    break;
                default:
                    w.Comment($"TODO: connection '{c.Name}' has unsupported "
                            + $"CreationName '{c.CreationName}' — manual migration required");
                    break;
            }
        }
        w.Indent(-2);
    }

    static void EmitParameters(YamlWriter w, DtsxPackage pkg)
    {
        /* Two sources of parameters with two different DataType enums:
         *   <DTS:Variable>      → VARENUM (VT_*) → MapVariableType
         *   <SSIS:Parameter>    → System.TypeCode → MapParameterType
         * Both emit into the same `parameters:` block (betl doesn't
         * distinguish scope).  We dedupe by id so a Variable and a
         * Parameter with the same name only emit once (Parameter wins,
         * since project params override package-level vars at runtime
         * in SSIS). */
        var userVars = pkg.Variables.Where(v => v.Namespace == "User").ToList();
        if (userVars.Count == 0 && pkg.Parameters.Count == 0) return;
        w.Line();
        w.Line("parameters:");
        w.Indent(2);
        var seen = new HashSet<string>();
        foreach (var p in pkg.Parameters)
        {
            string id = YamlWriter.Id(p.Name);
            if (!seen.Add(id)) continue;
            w.Line(id + ":");
            w.Indent(2);
            w.Line("type: " + MapParameterType(p.DataType));
            if (!string.IsNullOrEmpty(p.ValueRaw))
                w.Line("default: " + YamlWriter.Quote(p.ValueRaw));
            if (!string.IsNullOrEmpty(p.Description))
                w.Comment(p.Description);
            if (p.Sensitive) w.Comment("sensitive: true — store outside source control");
            w.Indent(-2);
        }
        foreach (var v in userVars)
        {
            string id = YamlWriter.Id(v.Name);
            if (!seen.Add(id)) continue;
            w.Line(id + ":");
            w.Indent(2);
            w.Line("type: " + MapVariableType(v.DataType));
            if (!string.IsNullOrEmpty(v.ValueRaw))
                w.Line("default: " + YamlWriter.Quote(v.ValueRaw));
            w.Indent(-2);
        }
        w.Indent(-2);
    }

    static string MapVariableType(int dtsType)
    {
        /* SSIS' DataType attribute on a Variable's value is a VARENUM
         * (Win32 VT_* / OLE-Automation Variant) code, NOT a .NET
         * System.TypeCode. Empirically verified against dtexec 16.0
         * on Linux: a Variable with DataType="8" + value "hello"
         * loads as a String, while DataType="18" + "hello" fails
         * to load (18 is VT_UI2, expects an unsigned-int parse). */
        return dtsType switch
        {
            2  or 3                            => "int",     /* VT_I2, VT_I4 */
            4  or 5  or 6  or 14               => "decimal", /* VT_R4, VT_R8, VT_CY, VT_DECIMAL */
            7                                  => "date",    /* VT_DATE */
            8                                  => "string",  /* VT_BSTR */
            11                                 => "bool",    /* VT_BOOL */
            16 or 17 or 18 or 19 or 20 or 21
              or 22 or 23                      => "int",     /* VT_I1..VT_UINT */
            _                                  => "string",
        };
    }

    /* <SSIS:Parameter>'s DataType property uses System.TypeCode (the
     * .NET enum), NOT VARENUM. Real Project.params files emit
     * DataType=18 for strings, which would be UInt16 in VARENUM but is
     * String in TypeCode. Keep the two mappings cleanly separate. */
    public static string MapParameterType(int typeCode)
    {
        return typeCode switch
        {
            3                       => "bool",    /* Boolean */
            5 or 6 or 7 or 8 or 9
              or 10 or 11 or 12     => "int",     /* SByte..UInt64 */
            13 or 14 or 15          => "decimal", /* Single, Double, Decimal */
            16                      => "date",    /* DateTime */
            18                      => "string",  /* String */
            _                       => "string",
        };
    }

    /* Translate an SSIS expression embedded in a property — typically
     * a runtime SqlStatementSource — into the same string with
     * @[$Project::X] / @[$User::X] references rewritten as betl
     * ${params.x} substitutions. Other SSIS expression syntax
     * (concatenation with `+`, casts like `(DT_STR, 50, 1252)`) is
     * left alone for the operator to clean up; the substitution alone
     * gets the parameterisation working in betl. */
    public static string TranslateSsisExpression(string ssisExpr)
    {
        if (string.IsNullOrEmpty(ssisExpr)) return ssisExpr;
        /* @[$Project::Name]  /  @[$Package::Name]  /  @[$User::Name]
         * /  @[$System::Name]   →   ${params.name}.
         * System:: refs (PackageName, MachineName, etc.) have no
         * parameter equivalent — translate them to ${params.X} so the
         * substitution is visible, but mark them with a TODO at the
         * call-site if you want to be picky. */
        var re = new System.Text.RegularExpressions.Regex(
            @"@\[\$(Project|Package|User|System)::([A-Za-z_][A-Za-z0-9_]*)\]");
        return re.Replace(ssisExpr, m =>
            "${params." + YamlWriter.Id(m.Groups[2].Value) + "}");
    }

    /* ============================================================== *
     *  Pipeline emission                                               *
     *                                                                  *
     *  SSIS' control-flow tree contains containers (Sequence, ForEach, *
     *  ForLoop) with nested executables and precedence constraints     *
     *  scoped per container. betl's pipeline is a flat list, so we:    *
     *    1. Walk the tree to assign each leaf a stable betl id and to  *
     *       compute each container's entry/exit leaf sets.             *
     *    2. Lower every constraint (which may span container           *
     *       boundaries) into leaf→leaf edges.                          *
     *    3. Emit leaves in source-tree order, attaching `after:` /     *
     *       `on_failure:` / `condition:` derived from incoming         *
     *       constraints. Containers themselves emit a comment header   *
     *       so the operator sees the original grouping; Foreach / For  *
     *       headers also explain the iteration-semantics loss (betl    *
     *       has no loop construct yet).                                *
     * ============================================================== */

    static void EmitPipeline(YamlWriter w, DtsxPackage pkg, bool verbose)
    {
        if (pkg.Executables.Count == 0) return;

        /* ---- Phase 1: catalogue all leaves and containers. ---- */
        var refToLeafId = new Dictionary<string, string>();      // exe RefId → betl step id (leaves only)
        var leavesInOrder = new List<DtsxExecutable>();          // depth-first leaves
        var idCollisions = new Dictionary<string, int>();        // base id → suffix counter

        void Catalogue(DtsxExecutable exe)
        {
            if (exe.IsContainer)
            {
                foreach (var child in exe.Children) Catalogue(child);
                return;
            }
            string baseId = YamlWriter.Id(exe.Name);
            string id = baseId;
            if (idCollisions.TryGetValue(baseId, out int n))
            {
                idCollisions[baseId] = n + 1;
                id = $"{baseId}_{n + 1}";
            }
            else
            {
                idCollisions[baseId] = 1;
            }
            refToLeafId[exe.RefId] = id;
            leavesInOrder.Add(exe);
        }
        foreach (var exe in pkg.Executables) Catalogue(exe);

        /* ---- Phase 2: compute entry / exit leaf sets per container. ---- *
         * For a container C, entry leaves = leaves reachable from C with no
         * incoming constraint *inside* C. Exit leaves = same with no
         * outgoing constraint inside C. Used to lower a constraint
         * crossing C's boundary into leaf-to-leaf edges. */
        var entryLeaves = new Dictionary<string, List<string>>();
        var exitLeaves  = new Dictionary<string, List<string>>();

        void CollectLeafRefIds(DtsxExecutable exe, List<string> acc)
        {
            if (exe.IsContainer)
                foreach (var c in exe.Children) CollectLeafRefIds(c, acc);
            else acc.Add(exe.RefId);
        }

        void ComputeEntryExit(DtsxExecutable container)
        {
            var insideLeafRefIds = new List<string>();
            foreach (var c in container.Children) CollectLeafRefIds(c, insideLeafRefIds);

            var hasIncoming = new HashSet<string>();
            var hasOutgoing = new HashSet<string>();
            foreach (var p in container.Precedence)
            {
                /* Constraint endpoints may name a child container; expand
                 * the endpoint via the inner entry/exit maps we computed
                 * earlier (recursion is bottom-up so inner sets are ready). */
                foreach (var f in LeafRefsForEndpoint(container, p.FromRefId, exitLeaves))
                    hasOutgoing.Add(f);
                foreach (var t in LeafRefsForEndpoint(container, p.ToRefId, entryLeaves))
                    hasIncoming.Add(t);
            }
            var entries = new List<string>();
            var exits   = new List<string>();
            foreach (var r in insideLeafRefIds)
            {
                if (!hasIncoming.Contains(r)) entries.Add(r);
                if (!hasOutgoing.Contains(r)) exits.Add(r);
            }
            entryLeaves[container.RefId] = entries;
            exitLeaves[container.RefId]  = exits;
        }

        void WalkContainersBottomUp(DtsxExecutable exe)
        {
            if (!exe.IsContainer) return;
            foreach (var c in exe.Children) WalkContainersBottomUp(c);
            ComputeEntryExit(exe);
        }
        foreach (var top in pkg.Executables) WalkContainersBottomUp(top);

        /* ---- Phase 3: lower constraints to leaf-to-leaf edges. ---- */
        var perLeafIncoming = new Dictionary<string, List<DtsxPrecedence>>();
        void RegisterEdge(string toLeaf, DtsxPrecedence p)
        {
            if (!perLeafIncoming.TryGetValue(toLeaf, out var list))
            {
                list = new List<DtsxPrecedence>();
                perLeafIncoming[toLeaf] = list;
            }
            list.Add(p);
        }
        void LowerConstraints(DtsxExecutable container, List<DtsxPrecedence> edges)
        {
            foreach (var p in edges)
            {
                var fromLeaves = LeafRefsForEndpoint(container, p.FromRefId, exitLeaves);
                var toLeaves   = LeafRefsForEndpoint(container, p.ToRefId,   entryLeaves);
                foreach (var f in fromLeaves)
                {
                    foreach (var t in toLeaves)
                    {
                        var lowered = new DtsxPrecedence
                        {
                            FromRefId  = f,
                            ToRefId    = t,
                            Value      = p.Value,
                            EvalOp     = p.EvalOp,
                            Expression = p.Expression,
                            LogicalAnd = p.LogicalAnd,
                        };
                        RegisterEdge(t, lowered);
                    }
                }
            }
            foreach (var c in container.Children)
            {
                if (c.IsContainer) LowerConstraints(c, c.Precedence);
            }
        }
        /* Root: synthesise a fake container holding pkg-level edges. */
        var rootShim = new DtsxExecutable { Kind = "Microsoft.Sequence", RefId = "__root__" };
        rootShim.Children.AddRange(pkg.Executables);
        LowerConstraints(rootShim, pkg.RootPrecedence);

        /* ---- Phase 4: emit. ---- */
        w.Line();
        w.Line("pipeline:");
        w.Indent(2);
        var emittedIds = new HashSet<string>();
        foreach (var top in pkg.Executables)
            EmitExecutable(w, pkg, top, refToLeafId, perLeafIncoming,
                           emittedIds, verbose, containerDepth: 0);
        w.Indent(-2);
    }

    /* Resolve an endpoint refId to the set of leaf refIds it represents.
     * If the endpoint names a leaf inside the container's subtree,
     * returns just that leaf. If it names a child container, expand to
     * that container's entry or exit leaves (already computed). */
    static List<string> LeafRefsForEndpoint(DtsxExecutable container,
        string endpoint, Dictionary<string, List<string>> innerMap)
    {
        var result = new List<string>();
        DtsxExecutable? Find(DtsxExecutable e)
        {
            if (e.RefId == endpoint) return e;
            if (e.IsContainer)
                foreach (var c in e.Children) { var r = Find(c); if (r != null) return r; }
            return null;
        }
        foreach (var child in container.Children)
        {
            var hit = Find(child);
            if (hit != null)
            {
                if (hit.IsContainer)
                {
                    if (innerMap.TryGetValue(hit.RefId, out var leaves))
                        result.AddRange(leaves);
                }
                else
                {
                    result.Add(hit.RefId);
                }
                break;
            }
        }
        return result;
    }

    /* Walk a container subtree depth-first; for each leaf, emit it with
     * a FlowAttrs derived from its incoming lowered constraints. */
    static void EmitExecutable(YamlWriter w, DtsxPackage pkg, DtsxExecutable exe,
        Dictionary<string, string> refToLeafId,
        Dictionary<string, List<DtsxPrecedence>> perLeafIncoming,
        HashSet<string> emittedIds, bool verbose, int containerDepth)
    {
        if (exe.IsContainer)
        {
            EmitContainerHeader(w, exe);
            foreach (var c in exe.Children)
                EmitExecutable(w, pkg, c, refToLeafId, perLeafIncoming,
                               emittedIds, verbose, containerDepth + 1);
            return;
        }

        /* Build FlowAttrs from incoming constraints. */
        var attrs = BuildFlowAttrs(exe, refToLeafId, perLeafIncoming, emittedIds);

        switch (exe.Kind)
        {
            case "Microsoft.Pipeline":
                EmitDataflow(w, pkg, exe, attrs, verbose);
                break;
            case "Microsoft.ExecuteSQLTask":
                Mappers.ExecuteSqlTask.Emit(w, pkg, exe, attrs);
                break;
            case "Microsoft.ScriptTask":
                Mappers.ScriptTask.Emit(w, pkg, exe, attrs);
                break;
            case "Microsoft.FileSystemTask":
                Mappers.FileSystemTask.Emit(w, pkg, exe, attrs);
                break;
            case "Microsoft.BulkInsertTask":
                Mappers.BulkInsertTask.Emit(w, pkg, exe, attrs);
                break;
            case "Microsoft.ExecuteProcess":
                Mappers.ExecuteProcessTask.Emit(w, pkg, exe, attrs);
                break;
            default:
                w.Line($"- id: {YamlWriter.Id(exe.Name)}");
                w.Indent(2);
                Mappers.FlowAttrs.Emit(w, attrs);
                w.Comment($"TODO: executable type '{exe.Kind}' not yet supported "
                        + "— manual migration required");
                w.Indent(-2);
                break;
        }
        if (refToLeafId.TryGetValue(exe.RefId, out var id)) emittedIds.Add(id);
    }

    /* Header comments for a container — Sequence is silent, Foreach /
     * For emit a flag-block explaining the iteration semantics that
     * doesn't survive the flatten. */
    static void EmitContainerHeader(YamlWriter w, DtsxExecutable exe)
    {
        if (exe.IsSequence)
        {
            w.Comment($"── sequence: {exe.Name} (children flattened) ──");
            return;
        }
        if (exe.IsForEachLoop)
        {
            w.Comment($"── ForEach Loop: {exe.Name} ─────────────────────────────");
            w.Comment("TODO: SSIS Foreach Loop has no betl equivalent yet.");
            string en = exe.ForeachEnumeratorType ?? "(unknown enumerator)";
            w.Comment($"      Enumerator: {en}");
            foreach (var kv in exe.ForeachEnumProps)
                w.Comment($"        {kv.Key} = {kv.Value}");
            if (exe.ForeachVarMappings.Count > 0)
                w.Comment($"      Variable mapping: {string.Join(", ", exe.ForeachVarMappings)}");
            w.Comment("      The body below will run ONCE under betl. Either:");
            w.Comment("        - drive iteration externally (cron/Airflow + --param), or");
            w.Comment("        - rewrite the body as a SQL set-based query.");
            return;
        }
        if (exe.IsForLoop)
        {
            w.Comment($"── For Loop: {exe.Name} ─────────────────────────────────");
            w.Comment("TODO: SSIS For Loop has no betl equivalent yet.");
            if (!string.IsNullOrEmpty(exe.ForLoopInit))
                w.Comment($"      Init:   {exe.ForLoopInit}");
            if (!string.IsNullOrEmpty(exe.ForLoopEval))
                w.Comment($"      While:  {exe.ForLoopEval}");
            if (!string.IsNullOrEmpty(exe.ForLoopAssign))
                w.Comment($"      Step:   {exe.ForLoopAssign}");
            w.Comment("      The body below will run ONCE under betl.");
            return;
        }
    }

    static Mappers.FlowAttrs? BuildFlowAttrs(DtsxExecutable exe,
        Dictionary<string, string> refToLeafId,
        Dictionary<string, List<DtsxPrecedence>> perLeafIncoming,
        HashSet<string> emittedIds)
    {
        if (!perLeafIncoming.TryGetValue(exe.RefId, out var incoming)
            || incoming.Count == 0) return null;

        var attrs = new Mappers.FlowAttrs();
        bool anyFailure    = false;
        bool anyCompletion = false;
        bool anyOr         = false;
        string? expr       = null;

        foreach (var p in incoming)
        {
            if (!refToLeafId.TryGetValue(p.FromRefId, out var fromId)) continue;
            if (!emittedIds.Contains(fromId))
            {
                /* Forward edge (target before source in source order).
                 * betl tolerates this — `after:` is a reference, not a
                 * file-order dependency — but flag for the operator. */
                attrs.Notes.Add($"forward edge: upstream `{fromId}` is "
                              + "declared later in the pipeline");
            }
            if (!attrs.After.Contains(fromId)) attrs.After.Add(fromId);
            if (p.Value == 1) anyFailure    = true;
            if (p.Value == 2) anyCompletion = true;
            if (!p.LogicalAnd) anyOr = true;
            if (p.EvalOp != 1 && !string.IsNullOrEmpty(p.Expression))
                expr ??= p.Expression;
        }

        if (anyFailure)
        {
            attrs.OnFailure = "continue";
            attrs.Notes.Add("TODO: SSIS Failure precedence — betl has no "
                          + "\"run only on upstream failure\" gate; this "
                          + "step will run regardless of upstream outcome.");
        }
        else if (anyCompletion)
        {
            attrs.OnFailure = "continue";
            attrs.Notes.Add("note: SSIS Completion precedence — runs "
                          + "regardless of upstream success/failure.");
        }
        if (anyOr)
            attrs.Notes.Add("TODO: SSIS LogicalAnd=False (any-of) "
                          + "convergence — betl's `after:` is all-of.");
        if (expr != null) attrs.Condition = expr;

        return attrs;
    }

    static void EmitDataflow(YamlWriter w, DtsxPackage pkg, DtsxExecutable exe,
                             Mappers.FlowAttrs? flow, bool verbose)
    {
        w.Line($"- id: {YamlWriter.Id(exe.Name)}");
        w.Indent(2);
        Mappers.FlowAttrs.Emit(w, flow);
        w.Line("type: dataflow");
        w.Line("steps:");
        w.Indent(2);

        /* Component-id map: refId → betl `id` (lower_snake_case from
         * the SSIS name) and refId → class for from-ref formatting
         * decisions. */
        var refToId    = exe.Components.ToDictionary(c => c.RefId,
                                                     c => YamlWriter.Id(c.Name));
        var refToClass = exe.Components.ToDictionary(c => c.RefId, c => c.ClassId);

        /* Predecessor map keyed by downstream component ref. Each
         * predecessor entry carries enough to format a port-aware
         * `from:` ref and to disambiguate multi-input downstreams (e.g.
         * Merge Join's Left vs Right input). */
        var predecessors = new Dictionary<string, List<Mappers.PredEdge>>();
        foreach (var p in exe.Paths)
        {
            if (!predecessors.TryGetValue(p.EndComponentRef, out var list))
            {
                list = new List<Mappers.PredEdge>();
                predecessors[p.EndComponentRef] = list;
            }
            string parentId = refToId.TryGetValue(p.StartComponentRef, out var pid)
                                 ? pid : YamlWriter.Id(p.StartComponentRef);
            string parentCls = refToClass.TryGetValue(p.StartComponentRef, out var pcl)
                                 ? pcl : "";
            list.Add(new Mappers.PredEdge
            {
                ParentId      = parentId,
                ParentPort    = p.StartPortName,
                ParentClassId = parentCls,
            });
        }

        foreach (var c in exe.Components)
        {
            predecessors.TryGetValue(c.RefId, out var preds);
            string? fromId = (preds != null && preds.Count > 0)
                                ? Mappers.PredEdge.From(preds[0]) : null;

            switch (c.ClassId)
            {
                /* Sources / sinks */
                case "Microsoft.OLEDBSource":
                    Mappers.OledbSource.Emit(w, pkg, c);
                    break;
                case "Microsoft.OLEDBDestination":
                    Mappers.OledbDestination.Emit(w, pkg, c, fromId);
                    break;
                case "Microsoft.SQLServerDestination":
                    Mappers.SqlServerDestination.Emit(w, pkg, c, fromId);
                    break;
                case "Microsoft.FlatFileSource":
                    Mappers.FlatFileSource.Emit(w, pkg, c);
                    break;
                case "Microsoft.FlatFileDestination":
                    Mappers.FlatFileDestination.Emit(w, pkg, c, fromId);
                    break;

                /* Transforms */
                case "Microsoft.ConditionalSplit":
                    Mappers.ConditionalSplit.Emit(w, pkg, c, fromId);
                    break;
                case "Microsoft.Aggregate":
                    Mappers.Aggregate.Emit(w, pkg, c, fromId);
                    break;
                case "Microsoft.Sort":
                    Mappers.Sort.Emit(w, pkg, c, fromId);
                    break;
                case "Microsoft.Lookup":
                    Mappers.Lookup.Emit(w, pkg, c, fromId);
                    break;
                case "Microsoft.MergeJoin":
                    Mappers.MergeJoin.Emit(w, pkg, c, preds);
                    break;
                case "Microsoft.UnionAll":
                    Mappers.UnionAll.Emit(w, pkg, c, preds);
                    break;
                case "Microsoft.Multicast":
                    Mappers.Multicast.Emit(w, pkg, c, fromId);
                    break;
                case "Microsoft.DerivedColumn":
                    Mappers.DerivedColumn.Emit(w, pkg, c, fromId);
                    break;
                case "Microsoft.DataConvert":
                    Mappers.DataConvert.Emit(w, pkg, c, fromId);
                    break;
                case "Microsoft.Pivot":
                case "Microsoft.PivotTransform":
                    Mappers.Pivot.Emit(w, pkg, c, fromId);
                    break;
                case "Microsoft.UnPivot":
                case "Microsoft.UnPivotTransform":
                    Mappers.Unpivot.Emit(w, pkg, c, fromId);
                    break;
                case "Microsoft.ScriptComponentHost":
                case "Microsoft.ScriptComponent":
                    Mappers.ScriptComponent.Emit(w, pkg, c, fromId);
                    break;

                /* New in 0.2.x: the rest of the SSIS default transform
                 * set. Some are real translations (Audit, CharacterMap,
                 * CopyColumn, Merge); the rest emit a passthrough +
                 * TODO so downstream wiring still validates. */
                case "Microsoft.RowCount":
                    Mappers.RowCount.Emit(w, pkg, c, fromId);
                    break;
                case "Microsoft.Audit":
                    Mappers.Audit.Emit(w, pkg, c, fromId);
                    break;
                case "Microsoft.CharacterMap":
                    Mappers.CharacterMap.Emit(w, pkg, c, fromId);
                    break;
                case "Microsoft.CopyMap":
                case "Microsoft.CopyColumn":
                    Mappers.CopyColumn.Emit(w, pkg, c, fromId);
                    break;
                case "Microsoft.OLEDBCommand":
                    Mappers.OledbCommand.Emit(w, pkg, c, fromId);
                    break;
                case "Microsoft.Merge":
                    Mappers.Merge.Emit(w, pkg, c, preds);
                    break;
                case "Microsoft.SCD":
                case "Microsoft.SlowlyChangingDimension":
                    Mappers.Scd.Emit(w, pkg, c, fromId);
                    break;
                case "Microsoft.PercentSampling":
                case "Microsoft.PercentageSampling":
                    Mappers.Sampling.Emit(w, pkg, c, fromId, isPercentage: true);
                    break;
                case "Microsoft.RowSampling":
                    Mappers.Sampling.Emit(w, pkg, c, fromId, isPercentage: false);
                    break;
                case "Microsoft.FuzzyLookup":
                    Mappers.RareStub.FuzzyLookup(w, c, fromId);
                    break;
                case "Microsoft.FuzzyGrouping":
                    Mappers.RareStub.FuzzyGrouping(w, c, fromId);
                    break;
                case "Microsoft.TermLookup":
                    Mappers.RareStub.TermLookup(w, c, fromId);
                    break;
                case "Microsoft.TermExtraction":
                    Mappers.RareStub.TermExtraction(w, c, fromId);
                    break;
                case "Microsoft.Cache":
                case "Microsoft.CacheTransform":
                    Mappers.RareStub.CacheTransform(w, c, fromId);
                    break;
                case "Microsoft.ExportColumn":
                    Mappers.RareStub.ExportColumn(w, c, fromId);
                    break;
                case "Microsoft.ImportColumn":
                    Mappers.RareStub.ImportColumn(w, c, fromId);
                    break;
                case "Microsoft.CDCSplitter":
                    Mappers.RareStub.CdcSplitter(w, c, fromId);
                    break;
                case "Microsoft.CDCSource":
                    Mappers.RareStub.CdcSource(w, c);
                    break;
                case "Microsoft.BalancedDataDistributor":
                    Mappers.RareStub.BalancedDataDistributor(w, c, fromId);
                    break;
                case "Microsoft.DQSCleansing":
                case "Microsoft.DataCorrectionComponent":
                    Mappers.RareStub.DqsCleansing(w, c, fromId);
                    break;
                case "Microsoft.DataMiningQuery":
                case "Microsoft.DataMiningModelTraining":
                    Mappers.RareStub.DataMiningQuery(w, c, fromId);
                    break;

                default:
                    w.Line($"- id: {YamlWriter.Id(c.Name)}");
                    w.Indent(2);
                    w.Comment($"TODO: component class '{c.ClassId}' not yet "
                            + "supported — manual migration required");
                    if (fromId != null) w.Line($"from: {fromId}");
                    w.Indent(-2);
                    break;
            }
        }
        w.Indent(-2);
        w.Indent(-2);
    }
}
